version: "3"
services:
  web:
    # image: grimapps/simpleapp:3.0
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
  redis:
    image: "redis:alpine"
